### ISSUE TITLE
Cannot find module '../lib'

### ISSUE THREAD

**Issue by yangmingming** [OptiFi-Team/optifi-sdk#30]
$ npx ts-node scripts/bootstrap.ts
npx: installed 15 in 1.66s
Cannot find module '../lib'

<img width="639" alt="image" src="https://user-images.githubusercontent.com/3910971/165025036-e3e699ac-78b4-41fc-9d94-cba49c504b29.png">

**Comment by WayneAl** [comment]
You can run `tsc` to generate the `/lib`.
Also we will remove the import from `/lib` in future version.
Thank you.
